-- TV Shows (Cached Metadata)
create table public.shows (
  id bigint generated by default as identity primary key,
  tmdb_id integer not null unique,
  name text not null,
  poster_path text,
  backdrop_path text,
  first_air_date date,
  primary_color text,
  genres jsonb,
  show_cast jsonb,
  number_of_seasons integer
);

-- Update collection_items to support TV shows
alter table public.collection_items 
  add column media_type text check (media_type in ('movie', 'tv')) default 'movie',
  add column show_id bigint references public.shows(id),
  add column season_number integer;

-- Make movie_id nullable since it can be a show
alter table public.collection_items alter column movie_id drop not null;

-- Update unique constraint to handle shows and seasons
-- First drop the old one
alter table public.collection_items drop constraint collection_items_user_id_movie_id_format_key;

-- Add new unique constraint
-- For movies: (user_id, movie_id, format)
-- For TV: (user_id, show_id, format, season_number)
-- We'll use a unique index for this complexity
create unique index collection_items_unique_movie_idx on public.collection_items (user_id, movie_id, format) where media_type = 'movie';
create unique index collection_items_unique_tv_idx on public.collection_items (user_id, show_id, format, season_number) where media_type = 'tv';

-- Add RLS for shows
alter table public.shows enable row level security;
create policy "Shows are viewable by everyone" on public.shows for select using (true);
create policy "Authenticated users can insert shows" on public.shows for insert with check (auth.role() = 'authenticated');
create policy "Authenticated users can update shows" on public.shows for update using (auth.role() = 'authenticated');
