-- Movies (Cached Metadata)
create table public.movies (
  id bigint generated by default as identity primary key,
  tmdb_id integer not null unique,
  title text not null,
  poster_path text,
  backdrop_path text,
  release_date date,
  primary_color text
);

-- Collection Items (The User's Library)
create table public.collection_items (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users not null,
  movie_id bigint references public.movies(id) not null,

  -- Core Tracking
  format text check (format in ('VHS', 'DVD', 'BluRay', '4K', 'Digital')) not null,
  status text check (status in ('owned', 'wishlist')) default 'owned' not null,

  -- The Vibe Features
  is_on_display boolean default false,
  is_grail boolean default false,
  digital_provider text,
  condition text,
  notes text,

  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, movie_id, format)
);

-- Enable RLS
alter table public.movies enable row level security;
alter table public.collection_items enable row level security;

-- Movies: anyone can read, authenticated can insert/update (for caching from TMDB)
create policy "Movies are viewable by everyone"
  on public.movies for select using (true);

create policy "Authenticated users can insert movies"
  on public.movies for insert with check (auth.role() = 'authenticated');

create policy "Authenticated users can update movies"
  on public.movies for update using (auth.role() = 'authenticated');

-- Collection items: users can only access their own
create policy "Users can view own collection"
  on public.collection_items for select using (auth.uid() = user_id);

create policy "Users can insert own collection"
  on public.collection_items for insert with check (auth.uid() = user_id);

create policy "Users can update own collection"
  on public.collection_items for update using (auth.uid() = user_id);
